services:
  mongo:
    build: ./db
  server:
    build: ./server
    ports:
      - 8443:443
    environment:
      DB_CONN_STRING: mongodb://pastebin:pastebin@mongo:27017/pastebin
      DISABLE_HTML_ESCAPE: 0