services:
  mongo:
    build: ./db
  server:
    build: 
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      DB_CONN_STRING: mongodb://pastebin:pastebin@mongo:27017/pastebin
      DISABLE_HTML_ESCAPE: 0
      ENABLE_GRPC: 1
    ports:
      - 80:80
      - 443:443
      - 50051:50051
  client:
    build: 
      context: .
      dockerfile: ./client/Dockerfile
    volumes:
      - ./client:/pastebin/client:rw
